package com.dicoding.myxgame.model

import com.dicoding.myxgame.R


object FakeDataset {
    val gameDataset = listOf(
        Game(1, "Syberia 3", "Xbox One", "Apr 25, 2017", "Puzzle & trivia","Koalabs Studio", "Microids", R.drawable.syberia, "The limitless imagination of Benoît Sokal continues in Syberia 3, focusing on an entirely new adventure. After abandoning the island, Kate is found dying on the edge of a river by the Youkole tribe, a nomadic people migrating with their snow ostriches. Stuck in Valsembor village, together they must find a way to continue their journey in a race against their enemies and unexpected obstacles, not to mention Kate's past, which catches up with her." ),
        Game(2, "Sheltered", "Xbox One", "Mar 15, 2016", "Simulation","Unicube & Team17 Digital Ltd", "Team17 Digital Ltd.", R.drawable.sheltered,"Building upon the original 2015 fan-favourite, Sheltered 2 brings new challenges and deeper strategic gameplay. You are tasked with creating a leader and building up your faction whilst managing resources and tackling threats both natural and human. Everything from starvation and dehydration to radiation poisoning and enemy raids can prove fatal." ),
        Game(3, "Grounded", "Xbox One", "Sep 27, 2022", "Role Playing","Obsidian Entertainment", "Xbox Game Studios", R.drawable.grounded,"The world is a vast, beautiful, and dangerous place – especially when you have been shrunk to the size of an ant. Explore, build and survive together in this first-person, multiplayer, survival adventure. Can you thrive alongside the hordes of giant insects, fighting to survive the perils of the backyard?" ),
        Game(4, "Bayonetta", "Xbox One", "Feb 18, 2020", "Unknown","PlatinumGames Inc", "SEGA", R.drawable.bayonetta,"Bayonetta. The last survivor of an ancient witch clan who keep the balance between light, dark and chaos. Entombed to protect herself – and the world as we know it – Bayonetta is discovered and revived after 500 years, sparking a chain of events with cataclysmic repercussions." ),
        Game(5, "Battletoads", "Xbox One", "Aug 20, 2020", "Platformer","Dlala Studios", "Rare Ltd", R.drawable.battletoads,"The wait is over! Rash, Zitz and Pimple are returning at last to smash-hit their way through an all-new action-packed adventure of choreographed chaos, and couch co-op may never be the same again."),
        Game(6, "Halo Wars 2", "Xbox One", "Feb 21, 2017", "Simulation","Creative Assembly", "Microsoft Studios", R.drawable.halo_wars2,"Real-time strategy makes an explosive return to the Halo universe in Halo Wars 2. Lead Spartans, Warthogs and other classic Halo fighting forces in a brutal war against a terrifying new enemy on the biggest Halo battlefield ever." ),
        Game(7, "Torchlight III", "Xbox One", "Oct 13, 2020", "Role Playing","Echtra Inc", "Gearbox Publishing", R.drawable.torchlight,"It been a century since the events of Torchlight II, and the Ember Empire is in decline. In Torchlight III, Novastraia is again under threat of invasion and it up to you to defend against the Netherim and its allies. Gather your wits and brave the frontier to find fame, glory, and new adventures!" ),
        Game(8, "Castlevania", "Xbox 360", "Oct 25, 2013", "Action & Adventure","Mercury Steam Entertainment", "Konami", R.drawable.castlevania,"Soma Cruz, a young high school exchange student in Japan, is somehow involved in the eternal cycle of reincarnation of the Dark Lord himself. What role does Soma play in all of this? Will he be able to return to his own world?" ),
        Game(9, "Desperados III", "Xbox One", "Jun 16, 2020", "Unknown","Mimimi Games", "THQ Nordic", R.drawable.desperados,"Desperados III is a story-driven, hardcore tactical stealth game, set in a ruthless Wild West scenario." ),
        Game(10, "Mega Man", "Xbox One", "Feb 25, 2020", "Platformer","CAPCOM Co Ltd", "APCOM Co Ltd", R.drawable.mega_man,"Mega Man is back! The newest entry in this iconic series blends classic, challenging 2D platforming action with a fresh look." ),
        Game(11, "Forza Horizon", "Xbox One", "Oct 1, 2018", "Simulation","Playground Games", "Microsoft Studios", R.drawable.forza_horizon,"Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of the world’s greatest cars."),
        Game(12, "RIDE 4", "Xbox One", "Oct 7, 2020", "Simulation","Milestone", "Milestone", R.drawable.ride4,"Are you ready to live the best gaming experience that a motorcycle fan can get RIDE 4 will spark your competitive soul with hundreds of bikes, dozens of tracks and a whole new level of realism."),
        Game(13, "Stray", "Xbox One", "Aug 10, 2023", "Action & Adventure","BlueTwelve Studio", "Annapurna Interactive", R.drawable.stray,"Lost, alone and separated from family, a stray cat must untangle an ancient mystery to escape a long-forgotten city." ),
        Game(14, "Hogwarts", "Xbox One", "Feb 10, 2023", "Role Playing","Avalanche Software", "Warner Bros", R.drawable.hogwarts,"Hogwarts Legacy is an open-world action RPG set in the world first introduced in the Harry Potter books. Embark on a journey through familiar and new locations as you explore and discover magical beasts, customize your character and craft potions, master spell casting, upgrade talents and become the wizard you want to be." ),
        Game(15, "Cult of the Lamb", "Xbox One", "May 24, 2023", "Culturist","Massive Monster", "Devolver Digital", R.drawable.cult,"Cult of the Lamb casts players in the role of a possessed lamb saved from annihilation by an ominous stranger, and must repay their debt by building a loyal following in his name. Start your own cult in a land of false prophets, venturing out into diverse and mysterious regions to build a loyal community of woodland Followers and spread your Word to become the one true cult." ),
    )
}